services:
  delivery-db:
    image: postgres:alpine
    container_name: delivery-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - delivery-db-data:/var/lib/postgresql/data

  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    depends_on:
      - delivery-db
    links:
      - delivery-db
    ports:
      - '3003:3000'
    env_file:
      - .env.docker
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

volumes:
  delivery-db-data: